# Generated by Django 2.2.6 on 2019-12-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='type', max_length=255, null=True)),
                ('problemdes', models.CharField(blank=True, db_column='problem_des', max_length=3000, null=True)),
            ],
            options={
                'db_table': 'problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raisepro',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('userno', models.IntegerField(blank=True, db_column='userNo', null=True)),
            ],
            options={
                'db_table': 'raisepro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReconRle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtype', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recon_rle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('problemno', models.IntegerField(db_column='problemNo', primary_key=True, serialize=False)),
                ('solverno', models.IntegerField(blank=True, db_column='solverNo', null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_enduml', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'solve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeRefer',
            fields=[
                ('problemno', models.IntegerField(db_column='problemNo', primary_key=True, serialize=False)),
                ('string', models.CharField(blank=True, db_column='String', max_length=255, null=True)),
            ],
            options={
                'db_table': 'type_refer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.IntegerField(db_column='No', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phonenum', models.IntegerField(blank=True, db_column='phoneNum', null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
